export function json(data: unknown, status=200, extraHeaders: Record<string,string>={}) {
  return new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extraHeaders}});
}
export function getCookie(req: Request, name: string) { const c=req.headers.get('cookie')||''; const m=c.match(new RegExp('(?:^|; )'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'=([^;]*)')); return m?decodeURIComponent(m[1]):''; }
export async function sha256(text: string) { const b=await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text)); return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''); }
async function hmac(secret: string, msg: string) { const key=await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), {name:'HMAC',hash:'SHA-256'}, false, ['sign']); const sig=await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(msg)); return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_'); }
export function b64url(obj: any){ return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_'); }
export function unb64url(s: string){ return JSON.parse(decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/'))))); }
export async function signSession(payload: any, secret: string){ const body=b64url(payload); return body+'.'+await hmac(secret, body); }
export async function verifySession(token: string, secret: string){ try{ const [body,sig]=String(token||'').split('.'); if(!body||!sig)return null; const good=await hmac(secret, body); if(sig!==good)return null; const p=unb64url(body); if(p.exp && Date.now()>p.exp)return null; return p; }catch{return null;} }
export function memberSecret(env:any){ return env.MEMBER_SESSION_SECRET || env.ADMIN_SESSION_SECRET || 'development-member-session-secret'; }
export async function currentMember(env:any, req:Request){ const token=getCookie(req,'aibio_member'); const p=await verifySession(token, memberSecret(env)); if(!p?.email||!env.DB)return null; const row:any=await env.DB.prepare(`SELECT id,name,email,email_verified,status,comment_status,suspension_reason,comment_suspension_reason,created_at FROM members WHERE lower(email)=lower(?) LIMIT 1`).bind(p.email).first(); if(!row)return null; return {id:row.id,name:row.name,email:row.email,emailVerified:Number(row.email_verified||0)===1,status:row.status||'active',commentStatus:row.comment_status||'allowed',suspensionReason:row.suspension_reason||'',commentSuspensionReason:row.comment_suspension_reason||'',createdAt:row.created_at||''}; }
export async function requireMember(env:any, req:Request){ const m=await currentMember(env,req); if(!m) return {error: json({ok:false,error:'Member login required.'},401)}; return {member:m}; }
export async function adminSession(env:any, req:Request){ try{ const mod=await import('./admin/_session'); const local=await import('./admin/_local_credentials'); const secret=env.ADMIN_SESSION_SECRET || local.LOCAL_ADMIN_CREDENTIALS.ADMIN_SESSION_SECRET; const check=await mod.verifyAdminToken({...env,ADMIN_SESSION_SECRET:secret}, mod.getCookie(req)); return check?.ok ? check : null; }catch{return null;} }
export function parseJson(req:Request){ return req.json().catch(()=>({})); }
