import { currentMember, json, parseJson, requireMember } from '../../_shared';
const BYPASS='changyuraptor.dinosaur@gmail.com';
function safeJson(x:any){try{return JSON.stringify(x||{});}catch{return '{}';}}
function parseManuscript(row:any){let m:any={};try{m=JSON.parse(row.manuscript_json||'{}')}catch{};return {...m,id:row.id,memberEmail:row.member_email,title:row.title||m.title||'',submissionCategory:row.submission_category||m.submissionCategory||'AI Research',topic:row.research_area||m.topic||'',paymentStatus:row.payment_status||m.paymentStatus||'unpaid',reviewStatus:row.review_status||m.reviewStatus||'draft',status:m.status||row.review_status||'draft',articleId:row.article_id||m.articleId,version:row.version_label||m.version||'v1',versionNumber:row.version_number||m.versionNumber||1,siteId:row.site_id||m.siteId,publishedAt:row.published_at||m.publishedAt,createdAt:row.created_at,updatedAt:row.updated_at};}
async function storeImages(env:any, manuscript:any, email:string){ if(!env.AIBIO_STORAGE)return manuscript; const sections=Array.isArray(manuscript.sections)?manuscript.sections:[]; for(const sec of sections){ const img=String(sec.image||''); if(img.startsWith('/api/files/get?key=')) continue; const m=img.match(/^data:(image\/(?:jpeg|png));base64,(.+)$/); if(!m) continue; const mime=m[1], b64=m[2]; const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0)); const key=`submissions/${email}/${manuscript.id||crypto.randomUUID()}/figures/${crypto.randomUUID()}.${mime.includes('png')?'png':'jpg'}`; await env.AIBIO_STORAGE.put(key, bin, {httpMetadata:{contentType:mime}}); if(env.DB) await env.DB.prepare(`INSERT OR REPLACE INTO app_files (id,owner_email,related_id,r2_key,mime_type,size_bytes) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),email,manuscript.id||'',key,mime,bin.byteLength).run().catch(()=>{}); sec.imageR2Key=key; sec.image=`/api/files/get?key=${encodeURIComponent(key)}`; } return manuscript; }
export async function onRequestGet({request,env}:any){const member=await currentMember(env,request); if(!member)return json({ok:false,error:'Member login required.'},401); const url=new URL(request.url); const id=url.searchParams.get('id'); let q=`SELECT * FROM member_manuscripts WHERE lower(member_email)=lower(?)`; const binds:any[]=[member.email]; if(id){q+=' AND id=?';binds.push(id);} q+=' ORDER BY updated_at DESC'; const rows:any[]=await env.DB.prepare(q).bind(...binds).all().then((r:any)=>r.results||[]); return json({ok:true,manuscripts:rows.map(parseManuscript)});}
export async function onRequestPost({request,env}:any){const r=await requireMember(env,request); if((r as any).error)return (r as any).error; const member=(r as any).member; if(member.status==='suspended')return json({ok:false,error:'Account suspended.'},403); const body:any=await parseJson(request); const action=String(body.action||'save'); let m=body.manuscript||body; if(!m.id)m.id='SUB-'+Date.now(); m.memberEmail=member.email; m.updatedAt=new Date().toISOString(); m=await storeImages(env,m,member.email); let payment=m.paymentStatus||'unpaid', review=m.reviewStatus||'draft'; if(action==='formal-submit'){ if(member.email.toLowerCase()===BYPASS){payment='waived';review='under_review';m.status='submitted';m.paymentStatus=payment;m.reviewStatus=review;m.submittedAt=new Date().toISOString();} else {payment=m.paymentStatus||'unpaid'; review='draft';} }
 await env.DB.prepare(`INSERT INTO member_manuscripts (id,member_email,title,submission_category,research_area,payment_status,payment_waived,payment_waiver_reason,paypal_order_id,review_status,manuscript_json,article_id,version_label,version_number,site_id,published_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,COALESCE((SELECT created_at FROM member_manuscripts WHERE id=?),CURRENT_TIMESTAMP),CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET title=excluded.title,submission_category=excluded.submission_category,research_area=excluded.research_area,payment_status=excluded.payment_status,payment_waived=excluded.payment_waived,payment_waiver_reason=excluded.payment_waiver_reason,paypal_order_id=excluded.paypal_order_id,review_status=excluded.review_status,manuscript_json=excluded.manuscript_json,article_id=excluded.article_id,version_label=excluded.version_label,version_number=excluded.version_number,site_id=excluded.site_id,published_at=excluded.published_at,updated_at=CURRENT_TIMESTAMP`).bind(m.id,member.email,m.title||'',m.submissionCategory||'AI Research',m.topic||'',payment,payment==='waived'?1:0,payment==='waived'?'Testing/admin flow account':'',m.paypalOrderId||'',review,safeJson(m),m.articleId||'',m.version||'v1',m.versionNumber||1,m.siteId||'',m.publishedAt||'',m.id).run();
 return json({ok:true,manuscript:{...m,paymentStatus:payment,reviewStatus:review},requiresPayment:action==='formal-submit'&&payment!=='waived'});}
export async function onRequestDelete({request,env}:any){const r=await requireMember(env,request); if((r as any).error)return (r as any).error; const member=(r as any).member; const id=new URL(request.url).searchParams.get('id')||''; if(!id)return json({ok:false,error:'id required'},400); await env.DB.prepare(`UPDATE member_manuscripts SET review_status='deleted', deleted_from=review_status, deleted_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=? AND lower(member_email)=lower(?)`).bind(id,member.email).run(); return json({ok:true});}
